// <auto-generated />
namespace GigHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class populate_Genre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populate_Genre));
        
        string IMigrationMetadata.Id
        {
            get { return "202004161101528_populate_Genre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
